#
# Apply a full oci setup 
class oci_profile::configuration(
  Optional[String] $before_tenants        = undef,
  Optional[String] $tenants               = undef,
  Optional[String] $after_tenants         = undef,
  Optional[String] $before_compartments   = undef,
  Optional[String] $compartments          = undef,
  Optional[String] $after_compartments    = undef,
  Optional[String] $before_identity       = undef,
  Optional[String] $identity              = undef,
  Optional[String] $after_identity        = undef,
  Optional[String] $before_key_management = undef,
  Optional[String] $key_management        = undef,
  Optional[String] $after_key_management  = undef,
  Optional[String] $before_budget         = undef,
  Optional[String] $budget                = undef,
  Optional[String] $after_budget          = undef,
  Optional[String] $before_network        = undef,
  Optional[String] $network               = undef,
  Optional[String] $after_network         = undef,
  Optional[String] $before_block_storage  = undef,
  Optional[String] $block_storage         = undef,
  Optional[String] $after_block_storage   = undef,
  Optional[String] $before_object_storage = undef,
  Optional[String] $object_storage        = undef,
  Optional[String] $after_object_storage  = undef,
  Optional[String] $before_file_storage   = undef,
  Optional[String] $file_storage          = undef,
  Optional[String] $after_file_storage    = undef,
  Optional[String] $before_instances      = undef,
  Optional[String] $instances             = undef,
  Optional[String] $after_instances       = undef,
){
  easy_type::ordered_steps([
    'oci_profile::tenants',
    'oci_profile::compartments',
    'oci_profile::identity',
    'oci_profile::key_management',
    'oci_profile::budget',
    'oci_profile::network',
    'oci_profile::block_storage',
    'oci_profile::object_storage',
    'oci_profile::file_storage',
    'oci_profile::instances',
  ])
}
